TheBLVD/mammoth

README

Update spacing 2

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
Mammoth/Views/Cells/LoadMoreCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeaderExtension.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
Mammoth/Views/Cells/PostCardCell/PostCardPoll.swift
Mammoth/Views/FollowButton.swift

[benoit/mam-3493-possible-scrolling-performance-improvements](https://linear.app/theblvd/issue/MAM-3493/possible-scrolling-performance-improvements)

MAM-3493-possible-scrolling-performance-improvements

---

Mammoth/Screens/Composer/PollViewController.swift

Match the colors of the New Post button.

MAM-3471-done-button-on-polls-is-wrong-color

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Models/InstanceCardModel.swift
Mammoth/Models/PostCardModel.swift
Mammoth/Models/UserCardModel.swift
Mammoth/Screens/DetailScreen/DetailViewModel.swift
Mammoth/Screens/DiscoveryScreen/DiscoverSuggestionsViewModel.swift
Mammoth/Screens/DiscoveryScreen/DiscoveryViewModel.swift
Mammoth/Screens/DiscoveryScreen/InstancesViewController.swift
Mammoth/Screens/DiscoveryScreen/InstancesViewModel.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
Mammoth/Screens/HomeScreen/Views/LatestPill.swift
Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
Mammoth/Screens/ProfileScreen/Views/ProfileCoverImage.swift
Mammoth/Screens/Registration/SetupAccountsViewModel.swift
Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
Mammoth/Utils/Extensions/UIImage+Utils.swift
Mammoth/Utils/Extensions/UIImageView+Caching.swift
Mammoth/Utils/SDImageTransformers.swift
Mammoth/Views/AccountSwitcherButton.swift
Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardImageAttachment.swift
Mammoth/Views/Cells/PostCardCell/PostCardImageCollectionCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

https://linear.app/theblvd/issue/MAM-3499/performance-image-transforming-decoding-and-caching

MAM-3499-performance-image-transforming-decoding-and-caching

---

Mammoth/Screens/DetailScreen/DetailViewController.swift
Mammoth/Screens/DiscoveryScreen/PostResultsViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
Mammoth/Utils/Extensions/UIView+Constraints.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
Mammoth/Views/FollowButton.swift

https://linear.app/theblvd/issue/MAM-3519/performance-postcardcell-variants-to-limit-expensive-relayouts

MAM-3519-performance-postcardcell-variants-to-limit-expensive

---

Mammoth/Screens/Registration/IntroViewController.xib

- just updated the button text
- Xcode adjusted some colors because floats

MAM-3512-wording-tweak-to-login-screen

---

Mammoth/Models/PostCardModel.swift
Mammoth/Screens/HomeScreen/NewsFeedViewController.swift

https://linear.app/theblvd/issue/MAM-3521/performance-cache-cell-heights-and-associate-value-with-postcardmodel

MAM-3521-performance-cache-cell-heights-and-associate-value-with

---

Mammoth/Screens/Composer/NewPostViewController.swift

- update icons to FontAwesome
- handle wider language codes
- draw to spec

MAM-3543-update-some-icons-in-the-composer-toolbar

---

Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

https://linear.app/theblvd/issue/MAM-3565/gif-avatars-are-not-getting-rounded

MAM-3565-gif-avatars-are-not-getting-rounded

---

Mammoth/Utils/Extensions/UIView+Constraints.swift
Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
Mammoth/Views/Cells/PostCardCell/PostCardPoll.swift
Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift

Includes fix for disappearing GIF and videos after feed update 
[MAM-3556](https://linear.app/theblvd/issue/MAM-3556/gifs-removed-from-posts-when-a-timeline-updates-after-scrolling)
[MAM-3555](https://linear.app/theblvd/issue/MAM-3555/video-not-displaying)
and a few feed AutoLayout optimizations and fixes
https://linear.app/theblvd/issue/MAM-3564/performance-fix-autolayout-issues-after-feed-perf-changes

MAM-3564-performance-fix-autolayout-issues-after-feed-perf-changes

---

Mammoth/Managers/FollowManager.swift
Mammoth/Models/PostCardModel.swift
Mammoth/Models/PostCardTypes.swift
Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
Mammoth/Services/Backend/AccountService.swift
Mammoth/Utils/PostActions.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

https://linear.app/theblvd/issue/MAM-3567/incorrect-posts-are-showing-up-on-peoples-profile

MAM-3567-incorrect-posts-are-showing-up-on-peoples-profile

---

Mammoth/Screens/ProfileScreen/ProfileViewModel.swift

https://linear.app/theblvd/issue/MAM-3569/profile-avatar-image-reloads-after-already-being-loaded

MAM-3569-profile-avatar-image-reloads-after-already-being-loaded

---

Mammoth/Managers/StatusCache.swift
Mammoth/Models/PostCardModel.swift
Mammoth/Services/Backend/MastodonKit/Models/URL+Mastodon.swift

These changes depend on a new API endpoint, to be deployed to https://feature.moth.social.
https://linear.app/theblvd/issue/MAM-3516/quote-posts-better-for-threads

MAM-3516-quote-posts-better-for-threads

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Models/PostCardModel.swift
Mammoth/Screens/Settings/About.rtf
Mammoth/Services/Backend/MastodonKit/Models/Card.swift
Mammoth/Utils/Extensions/UIImageView+Caching.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift

- Attempt to fix changing images in post
- Fixing constraint issues with posts with images
- Show blurhash as placeholder image
https://linear.app/theblvd/issue/MAM-3579/images-in-posts-change-correct-after-a-few-seconds-after-
loading

MAM-3579-images-in-posts-change-correct-after-a-few-seconds-after

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift

https://linear.app/theblvd/issue/MAM-3577/feed-jumps-while-dragging

MAM-3577-feed-jumps-while-dragging

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift

https://linear.app/theblvd/issue/MAM-3467/video-autoplays-in-post-details-with-auto-play-videos-and-gifs-turned

MAM-3467-video-autoplays-in-post-details-with-auto-play-videos-gifs

---

Mammoth/Managers/ChannelManager.swift
Mammoth/Screens/HomeScreen/FeedEditorViewController.swift
Mammoth/Views/Cells/FeedEditorCell.swift

https://linear.app/theblvd/issue/MAM-3596/unable-to-unsubscribe-from-smart-list-in-manage-feeds

MAM-3596-unable-to-unsubscribe-from-smart-list-in-manage-feeds

---

Mammoth/Models/PostCardModel.swift
Mammoth/Screens/DetailScreen/DetailViewModel.swift

https://linear.app/theblvd/issue/MAM-3597/seeing-cant-load-more-in-threads-post-details

MAM-3597-seeing-cant-load-more-in-threads-post-details

---

Mammoth/Models/PostCardModel.swift

https://linear.app/theblvd/issue/MAM-3548/retain-user-formatting-in-posts

MAM-3548-retain-user-formatting-in-posts

---

Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift

https://linear.app/theblvd/issue/MAM-3551/fade-in-follow-buttons

MAM-3551-fade-in-follow-buttons

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift

https://linear.app/theblvd/issue/MAM-3459/sometimes-mentions-sent-is-showing-no-posts

MAM-3459-sometimes-mentions-sent-is-showing-no-posts

---

Mammoth/Managers/AccountsManager/AcctData.swift

Use correct postingLanguage setting

MAM-3601-default-language-showing-public-sometimes

---

Mammoth/Managers/AccountsManager/AccountsManager.swift
Mammoth/Managers/AccountsManager/AcctHandler.swift

After updating ForYou settings from the network, it was overwriting other updated account information.

MAM-3603-im-seeing-onboarding-after-signing-in-an-going-through-it

---

Mammoth/Models/PostCardModel.swift
Mammoth/Utils/PostActions.swift

https://linear.app/theblvd/issue/MAM-3591/consider-adding-re-section-to-quote-posts
New format in various apps:

MAM-3591-consider-adding-re-section-to-quote-posts

---

Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardImageAttachment.swift

https://linear.app/theblvd/issue/MAM-3604/multiple-user-complaints-about-image-quality

MAM-3604-multiple-user-complaints-about-image-quality

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift

https://linear.app/theblvd/issue/MAM-3612/empty-face-pill-on-first-foryou-load

MAM-3612-empty-face-pill-on-first-foryou-load

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift

https://linear.app/theblvd/issue/MAM-3608/ui-froze-after-deleting-a-post

MAM-3608-ui-froze-after-deleting-a-post

---

Mammoth/AppDelegate.swift
Mammoth/Managers/AccountsManager/AccountsManager.swift
Mammoth/Managers/FeedsManager.swift
Mammoth/Managers/InstanceManager.swift
Mammoth/Managers/ModerationManager.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Caching.swift
Mammoth/Screens/Registration/SignInViewController.swift

[MAM-3618 : Don't log Disk.retrieve errors](https://linear.app/theblvd/issue/MAM-3618/dont-log-diskretrieve-errors)

MAM-3618-dont-log-diskretrieve-errors

---

.github/ISSUE_TEMPLATE/bug_report.yml

makes for some easy back end catches.

add instance address to the bug report template.

---

Mammoth/Managers/ToastNotification.swift
Mammoth/Models/MAMenu.swift
Mammoth/Models/PostCardTypes.swift
Mammoth/Services/Backend/AccountService.swift
Mammoth/Services/Backend/MastodonKit/Models/Report.swift
Mammoth/Services/Backend/StatusService.swift
Mammoth/Utils/PostActions.swift
Mammoth/Utils/UserActions.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

[MAM-942 : Report: Add Report Post button](https://linear.app/theblvd/issue/MAM-942/report-add-report-post-button)

MAM-942-report-add-report-post-button

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift

[MAM-3613 : Show loader on first Following feed load](https://linear.app/theblvd/issue/MAM-3613/show-loader-on-first-following-feed-load)

MAM-3613-show-loader-on-first-following-feed-load

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift

[MAM-3616 : App freezes when muting/unmuting accounts](https://linear.app/theblvd/issue/MAM-3616/app-freezes-when-mutingunmuting-accounts)

MAM-3616-app-freezes-when-mutingunmuting-accounts

---

Mammoth/Screens/Settings/TextFileViewController.swift

MAM-3638-about-pane-looks-transparent-in-vision-pro

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift

[MAM-3602 : Seeing "Can't load more" after a clean install, sign in with moth.social account](https://linear.app/theblvd/issue/MAM-3602/seeing-cant-load-more-after-a-clean-install-sign-in-with-mothsocial)

MAM-3602-seeing-cant-load-more-after-a-clean-install-sign-in-with

---

Mammoth/Models/PostCardModel.swift
Mammoth/Models/UserCardModel.swift
Mammoth/Utils/ParseTextAttachments.swift
Mammoth/Views/External/ActiveLabel/ActiveLabel.swift

[MAM-3083 : Custom Emojis not showing in Posts](https://linear.app/theblvd/issue/MAM-3083/custom-emojis-not-showing-in-posts)

MAM-3083-custom-emojis-not-showing-in-posts

---

Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift

[MAM-3657 : Hide quote post loader when loaded](https://linear.app/theblvd/issue/MAM-3657/hide-quote-post-loader-when-loaded)
https://github.com/TheBLVD/mammoth/assets/221925/792425ac-61b0-42f5-ad83-50a5e2453a5c

MAM-3657-hide-quote-post-loader-when-loaded

---

Mammoth/Models/MAMenu.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
Mammoth/Screens/ProfileScreen/Views/ProfileViewSettingsButton.swift

[MAM-3630 : Let's align Likes / Favorites](https://linear.app/theblvd/issue/MAM-3630/lets-align-likes-favorites)

MAM-3630-lets-align-likes-favorites

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Models/PostCardModel.swift
Mammoth/Models/PostCardTypes.swift
Mammoth/Models/UserCardModel.swift
Mammoth/Screens/Settings/About.rtf
Mammoth/Utils/PostActions.swift
Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
Mammoth/Views/Cells/UserCardCell/UserCardCell.swift

[MAM-3652 : Support *animated* custom emoji in post text and display name](https://linear.app/theblvd/issue/MAM-3652/support-animated-custom-emoji-in-post-text-and-display-name)

MAM-3652-support-animated-custom-emoji-in-post-text-and-display-name

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Screens/Composer/EmojiCell.swift
Mammoth/Screens/Composer/EmoticonPickerViewController.swift

- create EmojiCell (based on ImageCell)
- use scaleAspectFit for the emoji images
- remove extra cell setup calls from the viewController

MAM-3685-server-emoji-being-clipped-in-composer

---

Mammoth/Models/UserCardModel.swift
Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
Mammoth/Services/Backend/MastodonKit/Models/HashType.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
Mammoth/Views/Cells/UserCardCell/UserCardCell.swift

[MAM-3675 : Migrate Profile Header to MetaText](https://linear.app/theblvd/issue/MAM-3675/migrate-profile-header-to-metatext)

MAM-3675-migrate-profile-header-to-metatext

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift

[MAM-3637 : Bad timestamps or sorting in activity tab](https://linear.app/theblvd/issue/MAM-3637/bad-timestamps-or-sorting-in-activity-tab)

MAM-3637-bad-timestamps-or-sorting-in-activity-tab

---

Mammoth/Models/UserCardModel.swift
Mammoth/Services/Backend/MastodonKit/Models/Emoji.swift

- have UserCardModel check .emojis for equality
- add equality to Emoji

MAM-3703-usercardmodel-should-compare-emoji-to-be-equal

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

- make postTextLabel a MetaText (MetaLabel would not allow limiting to 4 lines AFAICT)

MAM-3701-custom-emojis-not-appearing-in-activity-tab

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

https://linear.app/theblvd/issue/MAM-3716/fix-blank-labels-in-activity-cells

MAM-3716-fix-blank-labels-in-activity-cells

---

Mammoth/Views/AccountSwitcherButton.swift

[MAM-3706 : Add "Account settings" option in account switcher](https://linear.app/theblvd/issue/MAM-3706/add-account-settings-option-in-account-switcher)

MAM-3706-add-account-settings-option-in-account-switcher

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

Set lineFragmentPadding to zero

MAM-3719-name-and-content-misaligned-in-activity-view

---

Mammoth/Views/Cells/LoadMoreCell.swift

Update "Load older posts" cell UI
https://github.com/TheBLVD/mammoth/assets/221925/fa7b1f64-b90e-48ce-9c24-dbc970400053
[MAM-3734 : Update "Load older posts" cell colors](https://linear.app/theblvd/issue/MAM-3734/update-load-older-posts-cell-colors)

MAM-3734-update-load-older-posts-cell-colors

---

Mammoth/Screens/EditFieldsViewController.swift
Mammoth/Screens/EditProfileViewController.swift

MAM-3715-remove-icons-from-edit-modals-on-profile

---

Mammoth/Models/PostCardModel.swift

Break the quote post -> quote post cycle for self-referencing quote posts.

MAM-3750-crash-looking-at-piuvaskolektivasocial

---

Mammoth/Screens/ExploreViewController.swift

MAM-3755-remove-header-tags-on-trends-page

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

Reverts TheBLVD/mammoth#314 (due to dependencies)

Revert "MAM-3752-multi-image-posts-in-activity-are-not-properly-defaulting-to"

---

Mammoth/Views/Cells/TextSizeCell.swift

Make constraint more flexible to avoid warning.

MAM-3763-seeing-constraint-issue-when-opening-settings-appearance

---

Mammoth/Screens/Composer/PollViewController.swift
Mammoth/Screens/EditProfileViewController.swift
Mammoth/Screens/FilterDetailsViewController.swift
Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
Mammoth/Screens/Settings/ComposerSettingsViewController.swift
Mammoth/Views/Cells/SelectionCell.swift

- change SelectionCell to be based on UITableViewCell.value1, instead of fully custom (with custom spacing)
- adjust callers to call new ivar names
- adjust callers to do less cell customization that is no longer needed

MAM-3727-appearance-settings-items-not-aligned-on-iphone-15-pro-max

---

Mammoth/Screens/Composer/NewPostViewController.swift

- add a 'custom emoji' button to the keyboard toolbar
- remove 'custom emoji' from the … menu

MAM-3718-should-custom-emoji-be-easier-to-access-in-the-composer

---

Mammoth/AppDelegate.swift
Mammoth/Managers/AccountsManager/AccountsManagerShim.swift
Mammoth/Models/GlobalStruct.swift
Mammoth/Screens/External/SKPhotoBrowser/SKAnimator.swift
Mammoth/Screens/Registration/SignUpViewController.swift
Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
Mammoth/Screens/iPad/ColumnViewController.swift
Mammoth/Screens/iPad/SidebarViewController.swift

- remove a bunch of unused globals
(Just trying to reduce some of the noise…)

MAM-3749-remove-unused-globals-inoverlayedscreen-others

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift

Update bookmarks even if there's only one new item.

MAM-3713-fix-issue-with-bookmark-fetching-threshold

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift

- Aspect ratio fixes for videos
- Accept swipes outside the gallery frame when the touch is on content of the scrollview
[MAM-3767 : Media Carousel - additional work](https://linear.app/theblvd/issue/MAM-3767/media-carousel-additional-work)

MAM-3767-media-carousel-additional-work

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

[MAM-3776 : Don't show carousel in activity](https://linear.app/theblvd/issue/MAM-3776/dont-show-carousel-in-activity)

MAM-3776-dont-show-carousel-in-activity

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

[MAM-3760 : Don't show Poll in activity](https://linear.app/theblvd/issue/MAM-3760/dont-show-poll-in-activity)

MAM-3760-dont-show-poll-in-activity

---

Mammoth/Services/Backend/MastodonKit/Models/Attachment.swift

[MAM-3724 : Image Size/cropping in Mammoth](https://linear.app/theblvd/issue/MAM-3724/image-sizecropping-in-mammoth)

MAM-3724-image-sizecropping-in-mammoth

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

[MAM-3759 : Posts in activity should adhere to user settings](https://linear.app/theblvd/issue/MAM-3759/posts-in-activity-should-adhere-to-user-settings)

MAM-3759-posts-in-activity-should-adhere-to-user-settings

---

Mammoth/Models/UserCardModel.swift
Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
Mammoth/Utils/UserActions.swift

[MAM-3777 : Enabling notifications on a profile returns a 404](https://linear.app/theblvd/issue/MAM-3777/enabling-notifications-on-a-profile-returns-a-404)

MAM-3777-enabling-notifications-on-a-profile-returns-a-404

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift

[MAM-3789 : Remove old code resolving merge issue](https://linear.app/theblvd/issue/MAM-3789/remove-old-code-resolving-merge-issue)

MAM-3789-remove-old-code-resolving-merge-issue

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
Mammoth/Views/Cells/UserCardCell/UserCardCell.swift

[MAM-3784 : Right-align image stack in New Post notification](https://linear.app/theblvd/issue/MAM-3784/right-align-image-stack-in-new-post-notification)

MAM-3784-right-align-image-stack-in-new-post-notification

---

Mammoth/Views/Cells/PostCardCell/PostCardMediaStack.swift

[MAM-3793 : Preload images and use blurhash in fullscreen view v2](https://linear.app/theblvd/issue/MAM-3793/preload-images-and-use-blurhash-in-fullscreen-view-v2)

MAM-3793-preload-images-and-use-blurhash-in-fullscreen-view-v2

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift

[MAM-3795 : Changing name settings to "Usertag" doesn't show anything](https://linear.app/theblvd/issue/MAM-3795/changing-name-settings-to-usertag-doesnt-show-anything)

MAM-3795-changing-name-settings-to-usertag-doesnt-show-anything

---

Mammoth/Models/PostCardModel.swift

[MAM-3799 : Quote posts are auto appending the image to the post](https://linear.app/theblvd/issue/MAM-3799/quote-posts-are-auto-appending-the-image-to-the-post)

MAM-3799-quote-posts-are-auto-appending-the-image-to-the-post

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift

[MAM-3798 : Random Image showing in Activity tab](https://linear.app/theblvd/issue/MAM-3798/random-image-showing-in-activity-tab)

MAM-3798-random-image-showing-in-activity-tab

---

Mammoth/Managers/RealtimeManager.swift

[MAM-3810 : Activity Notifications: prevent websockets to deconnect](https://linear.app/theblvd/issue/MAM-3810/activity-notifications-prevent-websockets-to-deconnect)

MAM-3810-activity-notifications-prevent-websockets-to-disconnect

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift

[MAM-3816 : PostCardCell constraint warning fixes](https://linear.app/theblvd/issue/MAM-3816/postcardcell-constraint-warning-fixes)

MAM-3816-postcardcell-constraint-warning-fixes

---

Mammoth.xcodeproj/project.pbxproj
MammothNotificationServiceExtension/NotificationService.swift
MammothNotificationServiceExtension/Utils/String+Helpers.swift

[MAM-3723 : Notification showing raw custom emoji shortcode](https://linear.app/theblvd/issue/MAM-3723/notification-showing-raw-custom-emoji-shortcode)

MAM-3723-notification-showing-raw-custom-emoji-shortcode

---

Mammoth/Services/Backend/MastodonKit/Client.swift

Only include the token when communicating to the user's instance.
Allow for the mothClient to use its token.
Allow certain URLs to use their tokens.

MAM-3823-mammoth-sends-the-user-token-to-unknown-servers

---

Mammoth/Screens/Composer/NewPostViewController.swift

- put up an alert if the user tries to upload more than one video, or a combination of video + image
- generalize the media error alert

MAM-3811-cannot-upload-image-video

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeaderExtension.swift
Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
Mammoth/Views/Cells/PostCardCell/PostCardMediaStack.swift
Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift

[MAM-3833 : Private mentions lost their highlight](https://linear.app/theblvd/issue/MAM-3833/private-mentions-lost-their-highlight)

MAM-3833-private-mentions-lost-their-highlight

---

Mammoth/Screens/DiscoveryScreen/DiscoverSuggestionsViewController.swift
Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
Mammoth/Views/Cells/ChannelCell.swift
Mammoth/Views/Cells/HashtagCell.swift
Mammoth/Views/FollowButton.swift
Mammoth/Views/StaticPic.swift

Update these to handle contrast change
- ActivityCardCell
- the Follow button
- the Discover tab views
- the Profile tab view

MAM-3854-posts-in-activity-arent-using-high-contrast

---

sample.env

Small update quality-of-life to the sample.env file for anyone trying to get the project compiling locally.

Added two missing keys from the sample.env file required by .arkana.yml

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift
Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

- pass in postCard data when configuring replyButton and likeButton
- use postCard.isPrivateMention when setting background colors
- track isPrivateMention in PostCardProfilePic as well

MAM-3862-high-contrast-issue-with-some-mentions-content

---

Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift

[MAM-3889 : like actions not sticking](https://linear.app/theblvd/issue/MAM-3889/like-actions-not-sticking)
[MAM-3894 : Like not working on post details](https://linear.app/theblvd/issue/MAM-3894/like-not-working-on-post-details)

MAM-3889-like-actions-not-sticking

---

Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift

Set likes/replies/reposts color to match the buttons

MAM-3881-likesrepliesreposts-line-should-be-same-color-as-view-details

---

Mammoth/Views/NewPostButton.swift

[MAM-3897 : Fix NewPost button text color](https://linear.app/theblvd/issue/MAM-3897/fix-newpost-button-text-color)

MAM-3897-fix-newpost-button-text-color

---

Mammoth/Views/ThinSlider.swift

MAM-3900-settings-appearance-slider-hard-to-read-in-high-contrast-mode

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Screens/Composer/AltTextViewController.swift
Mammoth/Screens/DiscoveryScreen/ChannelsViewController.swift
Mammoth/Screens/HomeScreen/FeedEditorViewController.swift
Mammoth/Screens/HomeScreen/HomeViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
Mammoth/Screens/TutorialOverlay/ArrowAlignment.swift
Mammoth/Screens/TutorialOverlay/TutorialOverlay.swift
Mammoth/Screens/TutorialOverlay/Types.swift
Mammoth/Screens/TutorialOverlay/Views/TextBubbleView.swift
Mammoth/Utils/NavigationHelpers.swift

- long press on home nav bar item
- tutorial for home bar item long-press
[MAM-3898 : Nav Cleanup - Feed quick jump menu](https://linear.app/theblvd/issue/MAM-3898/nav-cleanup-feed-quick-jump-menu)

MAM-3898-nav-cleanup-feed-quick-jump-menu

---

Mammoth/Models/UserCardTypes.swift
Mammoth/Screens/HomeScreen/HomeViewController.swift
Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
Mammoth/Screens/ProfileScreen/Views/ProfileViewSettingsButton.swift
Mammoth/Screens/TutorialOverlay/TutorialOverlay.swift
Mammoth/Screens/TutorialOverlay/Views/TextBubbleView.swift
Mammoth/Views/AccountSwitcherButton.swift
Mammoth/Views/CarouselNavigationHeader.swift
Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

[MAM-3908 : Nav Cleanup - Account switcher](https://linear.app/theblvd/issue/MAM-3908/nav-cleanup-account-switcher)

MAM-3908-nav-cleanup-account-switcher

---

Mammoth/Screens/ActivityScreen/ActivityViewController.swift
Mammoth/Screens/DiscoveryScreen/SearchHostViewController.swift
Mammoth/Screens/HomeScreen/HomeViewController.swift
Mammoth/Screens/HomeScreen/Views/Carousel/Carousel.swift
Mammoth/Screens/HomeScreen/Views/Carousel/CarouselFlowLayout.swift
Mammoth/Screens/HomeScreen/Views/Carousel/CarouselItem.swift
Mammoth/Screens/MentionsScreen/MentionsViewController.swift
Mammoth/Screens/UserListScreen/UserListViewController.swift

[MAM-3909 : Nav Cleanup - Feed carousel item menu](https://linear.app/theblvd/issue/MAM-3909/nav-cleanup-feed-carousel-item-menu)

MAM-3909-nav-cleanup-feed-carousel-item-menu

---

Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift

Use Feint Contrast for…
- likes/repost/replies labels
- View Details label
- url label in link preview

MAM-3920-theme-issues-for-hc-all-themes

---

Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift

https://github.com/TheBLVD/mammoth/assets/221925/90a16600-ef4a-4bc7-810a-2e35e496ea03
[MAM-3904 : Lets add a dedicated quote post button](https://linear.app/theblvd/issue/MAM-3904/lets-add-a-dedicated-quote-post-button)

MAM-3904-lets-add-a-dedicated-quote-post-button

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Utils/Extensions/UILabel+IsTruncated.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/ReadMoreButton.swift

[MAM-3910 : Post card read more button on text truncation](https://linear.app/theblvd/issue/MAM-3910/post-card-read-more-button-on-text-truncation)
https://github.com/TheBLVD/mammoth/assets/221925/1934729d-47d3-4f44-bd92-f97d438799b8

MAM-3910-post-card-read-more-button-on-text-truncation

---

Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift

[MAM-3927 : Attempt to fix but below quote post from Justin](https://linear.app/theblvd/issue/MAM-3927/attempt-to-fix-but-below-quote-post-from-justin)

MAM-3927-attempt-to-fix-but-below-quote-post-from-justin

---

Mammoth/Managers/AnalyticsManager.swift
Mammoth/Utils/Codable/MothSocialJWT.swift

- add gold status to JWT
- call activities() when gold status changes, and the user is a gold member

MAM-3924-include-is-gold-member-status-in-the-daily-checkin

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/ReadMoreButton.swift

[MAM-3936 : Put read more underneath the text](https://linear.app/theblvd/issue/MAM-3936/put-read-more-underneath-the-text)

MAM-3936-put-read-more-underneath-the-text

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/ReadMoreButton.swift

[MAM-3939 : Disable read more button](https://linear.app/theblvd/issue/MAM-3939/disable-read-more-button)

MAM-3939-disable-read-more-button

---

Mammoth/Models/PostCardTypes.swift

MAM-3932-post-actions-not-on-color-variable

---

Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift

Update colors on theme change.

MAM-3929-posts-from-users-wnotifs-turned-on-styling

---

Mammoth/Screens/EditProfileViewController.swift
Mammoth/Services/Backend/MastodonKit/Models/Account.swift

Akkoma accounts don't show timeline.

---

Mammoth/Models/PostCardModel.swift
Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift

https://linear.app/theblvd/issue/MAM-3975/no-image-indicator-in-postcardcell

MAM-3975-no-image-indicator-in-postcardcell

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+UnreadCount.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
Mammoth/Screens/HomeScreen/Views/UnreadIndicator.swift

https://linear.app/theblvd/issue/MAM-3985/bottom-up-feed-behavior-improvements
Justin's feedback:
- slide in/out animation on Unread Indicator
- more consistent unread count
- show JumpToNow pill faster when looking at an old feed (>24h old)
- don't discard JumpToNow pill if there's more content to load

MAM-3985-bottom-up-feed-behavior-improvements

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift

https://linear.app/theblvd/issue/MAM-3987/fix-unread-indicator-for-high-content-feeds

MAM-3987-fix-unread-indicator-for-high-content-feeds

---

Mammoth.xcodeproj/xcshareddata/xcschemes/Mastodon.xcscheme
Mammoth/Localizable.xcstrings
Mammoth/Screens/Settings/AppearanceSettingsViewController.swift

https://linear.app/theblvd/issue/MAM-3995/change-language-via-settings

MAM-3995-change-language-via-settings

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift

https://linear.app/theblvd/issue/MAM-4001/unread-pill-freezes-after-leaving-the-app

MAM-4001-unread-pill-freezes-after-leaving-the-app

---

Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift

https://linear.app/theblvd/issue/MAM-4016/add-to-list-popup-has-black-icons

MAM-4016-add-to-list-popup-has-black-icons

---

Mammoth/AppDelegate.swift
Mammoth/Localizable.xcstrings
Mammoth/Models/MAMenu.swift
Mammoth/Screens/Composer/AltTextViewController.swift
Mammoth/Screens/DiscoveryScreen/ChannelsViewController.swift
Mammoth/Screens/DiscoveryScreen/ChannelsViewModel.swift
Mammoth/Screens/DiscoveryScreen/HashtagsViewController.swift
Mammoth/Screens/DiscoveryScreen/InstancesViewController.swift
Mammoth/Screens/DiscoveryScreen/PostResultsViewController.swift
Mammoth/Screens/DiscoveryScreen/PostResultsViewModel.swift
Mammoth/Screens/FilterDetailsViewController.swift
Mammoth/Screens/FiltersViewController.swift
Mammoth/Screens/ForYouCustomizationScreen/ForYouCustomizationViewController.swift
Mammoth/Screens/HomeScreen/FeedEditorViewController.swift
Mammoth/Screens/LikedByMutedBlockedViewController.swift
Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Mammoth/Screens/ProfileScreen/Views/ProfileNavigationTitle.swift
Mammoth/Screens/Registration/SetupChannelsViewModel.swift
Mammoth/Screens/Settings/AccountsSettingsViewController.swift
Mammoth/Screens/UserListScreen/UserListViewModel.swift
Mammoth/Screens/iPad/ColumnViewController.swift
Mammoth/Screens/iPad/SidebarViewController.swift
Mammoth/Utils/IntentsStruct.swift
Mammoth/Views/Cells/DetailView.swift
Mammoth/Views/Cells/MessageCell.swift
Mammoth/Views/Cells/PostView.swift
Mammoth/Views/Cells/ProfileCell.swift
Mammoth/Views/Cells/SignInInstanceCell.swift
Mammoth/Views/Cells/UserCell.swift

had to do a single PR because or else i'd have to wait for merge bc of conflicts and all that.
also single commit because xcode crashed rendering localizable.xcstrings.

MAM-4012+4013+4017

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift

https://linear.app/theblvd/issue/MAM-4023/show-jumptonow-pill-faster

MAM-4023-show-jumptonow-pill-faster

---

Mammoth/Screens/Registration/SignInViewController.swift

we still need featurekit to take this input into account, though.
with TheBLVD/FeatureKit#10

MAM-3980-use-language-field-in-instancessocial

---

Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
Mammoth/Views/Cells/PostCardCell/PostCardMediaStack.swift

MAM-4046-blurhashes-still-have-wrong-size

---

Mammoth/Models/PostCardModel.swift
Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift
Mammoth/Utils/PostActions.swift
Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift

https://linear.app/theblvd/issue/MAM-4026/interaction-count-not-updating-in-the-timeline

MAM-4026-interaction-count-not-updating-in-the-timeline

---

Mammoth/Screens/HomeScreen/HomeViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift

[MAM-4048 : Double tap home is unreliable](https://linear.app/theblvd/issue/MAM-4048/double-tap-home-is-unreliable)

MAM-4048-double-tap-home-is-unreliable

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift

https://linear.app/theblvd/issue/MAM-4059/ghost-interactions-after-a-post-has-merged-in-remote-data

MAM-4059-ghost-interactions-after-a-post-has-merged-in-remote-data

---

Mammoth/Screens/Composer/PollViewController.swift
Mammoth/Utils/PostActions.swift

https://linear.app/theblvd/issue/MAM-4062/voting-on-polls-from-other-instances-fix

MAM-4062-voting-on-polls-from-other-instances-fix

---

Mammoth/Models/GlobalStruct.swift

https://linear.app/theblvd/issue/MAM-4063/enable-german

MAM-4063-enable-german

---

Mammoth/Services/Backend/MastodonKit/Requests/Search.swift
Mammoth/Services/Backend/SearchService.swift

https://linear.app/theblvd/issue/MAM-4065/crank-up-page-size-of-search-result

MAM-4065-crank-up-page-size-of-search-result

---

Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift

MAM-4032-listening-to-audio-not-working

---

Mammoth/Models/PostCardModel.swift

https://linear.app/theblvd/issue/MAM-4064/fix-issue-with-optimistic-likerepost-of-a-repost

MAM-4064-fix-issue-with-optimistic-likerepost-of-a-repost

---

Mammoth/Models/GlobalStruct.swift
Mammoth/Services/l10n/CrowdinService.swift

https://linear.app/theblvd/issue/MAM-4067/enable-spanish-and-italian-localization

MAM-4067-enable-spanish-and-italian-localization

---

Mammoth/Models/PostCardModel.swift

sorry for the previous oversight 😅

MAM-4071-interactions-going-up-but-not-back-down

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift

https://linear.app/theblvd/issue/MAM-4073/speed-up-feed-refresh-on-jumptonewest-and-2xtab

MAM-4073-speed-up-feed-refresh-on-jumptonewest-and-2xtab

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Caching.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift

https://linear.app/theblvd/issue/MAM-4077/fix-scroll-position-recovery-on-hydration

MAM-4077-fix-scroll-position-recovery-on-hydration

---

Mammoth/Screens/Composer/NewPostViewController.swift

the `postPiecesFromPost()` rewrite should be a WAY saner solution, that also accounts for URLs.
what it does is iterate word for word and push a new piece only if the current word would exceed the limit.

MAM-4084-urls-on-the-composer-should-always-be-23-characters-in

---

Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift

https://linear.app/theblvd/issue/MAM-4105/fix-for-post-card-header-height-issue-in-full-mode

MAM-4105-fix-for-post-card-header-height-issue-in-full-mode

---

Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift

https://linear.app/theblvd/issue/MAM-4104/fix-bug-with-feed-tab-double-tap

MAM-4104-fix-bug-with-feed-tab-double-tap

---

Mammoth/Screens/Registration/SignInViewController.swift

https://linear.app/theblvd/issue/MAM-4107/fix-client-issue-with-localized-instances-list

MAM-4107-fix-client-issue-with-localized-instances-list

---

Mammoth/Screens/Registration/SignInViewController.swift
Mammoth/Services/l10n/CrowdinService.swift

https://linear.app/theblvd/issue/MAM-4108/make-instances-list-sorting-work-of-pt-br

MAM-4108-make-instances-list-sorting-work-of-pt-br

---

Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift

https://linear.app/theblvd/issue/MAM-4109/repost-icon-didnt-light-up

MAM-4109-repost-icon-didnt-light-up

---

Mammoth/Localizable.xcstrings

this PR only exists to solve a merge conflict without complications.

Localizations of MAM-4087.

---

Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift

i see some weird visuals when unliking a post and those probably need to be fixed.

MAM-4124-interaction-counts-removing-post-metadata

---

Mammoth/Screens/EditFieldsViewController.swift

https://linear.app/theblvd/issue/MAM-4128/out-of-view-profile-fields-get-deleted-forever

MAM-4128-out-of-view-profile-fields-get-deleted-forever

---

Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift

this should've been added here in that other PR.

MAM-4142-small-oversight-in-mam-4125

---

Mammoth/AppDelegate.swift
Mammoth/Models/GlobalStruct.swift
Mammoth/Screens/Settings/SettingsViewController.swift
Mammoth/Utils/LinkOpener.swift

Fixes broken behavior from MAM-4161

PATCH-MAM-4161 browser selection

---

Mammoth/Views/Cells/PostCardCell/PostCardCell.swift

Don't show full width layout in details so as not to break the threading UI

MAM-4156: Add special case for full width for details cells

---

Mammoth.xcodeproj/project.pbxproj
Mammoth/Mammoth.entitlements
Mammoth/Managers/CloudSyncManager.swift
Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+Caching.swift
Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift

Initial changes and testing for iCloud position sync.

iCloud Sync
