TheBLVD/mammoth

- Mammoth/Screens/ProfileScreen/ProfileViewController.swift
PhotoPicker is initialized during app launch (27ms) but should only be initalized right before usage.
https://linear.app/theblvd/issue/MAM-3452/performance-init-photopicker-when-needed
> MAM-3452-performance-init-photopicker-when-needed

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
Instead of updating the unreadIndicator count and visibility (17ms) in `scrollViewDidScroll`, update it in `tableView:willDisplay:forRowAt` instead.
Calling `getCurrentCellIndexPath` (10ms) and `LatestPill.isEnabled.setter` (9ms) are expensive operations.
https://linear.app/theblvd/issue/MAM-3456/performance-dont-update-unreadindicator-on-scroll
> MAM-3456-performance-dont-update-unreadindicator-on-scroll

- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
Instead of adding and removing the badge from the view on each configure call, add the badge once, and use isHidden to show/hide it.
https://linear.app/theblvd/issue/MAM-3460/performance-create-the-profile-pic-badge-only-once
> MAM-3460-performance-create-the-profile-pic-badge-only-once

- Mammoth/Screens/ProfileScreen/ProfileViewController.swift
Only show the gear in the navbar if the user is past onboarding.
> MAM-3342-should-not-show-gear-in-upper-right-of-profile-when-onboarding

- Mammoth/Models/UserCardModel.swift
- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
...-profile
We only need to parse the description html on the profile screen (to make all links work correctly). In other places (UserCardCell) we use a stripped version of the description html and display that instead (faster)
https://linear.app/theblvd/issue/MAM-3469/performance-only-parse-user-description-html-when-loading-profile
> MAM-3469-performance-only-parse-user-description-html-when-loading

- Mammoth/Models/ActivityCardModel.swift
- Mammoth/Models/PostCardModel.swift
- Mammoth/Screens/DetailScreen/DetailViewController.swift
- Mammoth/Screens/DiscoveryScreen/PostResultsViewController.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
- Mammoth/Screens/ProfileScreen/ProfileViewController.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
In PostCardModel and ActivityCardModel we do not want time to be a computed property. Calling NSDateFormatter methods just-in-time seems to be expensive. Instead we set time once during init and update the value when the label is displayed using a custom time interval.
https://linear.app/theblvd/issue/MAM-3470/performance-time-should-not-be-computed-property
> MAM-3470-performance-time-should-not-be-computed-property

- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
- Mammoth/Views/Cells/PostCardCell/PostCardHeaderExtension.swift
- Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
When setting properties (eg. hashtagColor) on ActiveLabel, an expensive internal method `updateTextStorage` is being called. Limit these updates to a minimum, and when called, batch them using ActiveLabel's `customize` closure.
https://linear.app/theblvd/issue/MAM-3480/performance-update-activelabel-less-often
> MAM-3480-performance-update-activelabel-less-often

- Mammoth.xcodeproj/project.pbxproj
- Mammoth/AppCoordinator.swift
- Mammoth/Screens/Registration/SetupAccountsViewController.swift
- Mammoth/Screens/Registration/SetupAccountsViewModel.swift
- Mammoth/Screens/Registration/SetupMammothViewController.swift
- Mammoth/Screens/Registration/SetupMammothViewModel.swift
- Mammoth/Screens/Registration/SetupProfileController.swift
- Mammoth/Screens/Registration/SignInViewController.swift
- add third onboarding pane for Follow Mammoth
- filter mammoth@moth.social out of the list of suggested accounts
- no longer default to following mammoth@moth.social (was opt-out)
- skip suggesting following Mammoth if we're certain the user is already following it
> MAM-3472-remove-opt-out-behavior-for-mammoth-in-onboarding

- Mammoth.xcodeproj/project.pbxproj
- Mammoth/Models/GlobalStruct.swift
- Mammoth/Models/PostLanguages.swift
- Mammoth/Screens/Composer/NewPostViewController.swift
- Mammoth/Screens/Composer/TranslationComposeViewController.swift
- added PostLanguages class
- added TranslationComposeViewControllerDelegate
- extended NewPostViewController to add a language button
- removed the postLanguage global
> MAM-3497-make-switching-post-language-easier-more-user-friendly

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
https://linear.app/theblvd/issue/MAM-3559/revert-performance-changes-causing-feed-jumps
> MAM-3559-revert-performance-changes-causing-feed-jumps

- Mammoth/Managers/AccountsManager/AccountsManager.swift
- Mammoth/Managers/AccountsManager/AcctData.swift
- Mammoth/Managers/AccountsManager/AcctHandler.swift
- Mammoth/Models/PostLanguages.swift
- Mammoth/Services/Backend/MastodonKit/Models/Instance.swift
We now pick the post language in this priority:
1. previously picked language (from prefs), if available
2. default post language from their mastodon profile if available
3. their iOS current language (should always be available)
4. english if all else fails
> MAM-3561-investigate-account-language-setting-and-how-to-incorporate-it

- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
https://linear.app/theblvd/issue/MAM-3524/tapping-on-a-threads-username-yields-user-cant-be-found
Also related to https://github.com/TheBLVD/mammoth/issues/191
> MAM-3524-tapping-on-a-threads-username-yields-user-cant-be-found

- Mammoth/Managers/FollowManager.swift
- Mammoth/Services/Backend/AccountService.swift
When doing an account look up, use the Account lookup endpoint instead of the generic search endpoint.
Linear: https://linear.app/theblvd/issue/MAM-3566/profile-fetching-could-use-a-more-performant-function
Github Issues: https://github.com/TheBLVD/mammoth/issues/155
> MAM-3566-profile-fetching-could-use-a-more-performant-function

- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
No longer mask to bounds to prevent clipping
> MAM-3571-activity-badges-are-being-clipped

- Mammoth/Utils/PostActions.swift
https://linear.app/theblvd/issue/MAM-3573/tapping-on-avatar-in-activity-doesnt-navigate-to-profile
> MAM-3573-tapping-on-avatar-in-activity-doesnt-navigate-to-profile

- Mammoth/Screens/External/SKPhotoBrowser/SKPhotoBrowser.swift
- Mammoth/Screens/GalleryViewController.swift
- Mammoth/Utils/PostActions.swift
- Mammoth/Views/Cells/DetailImageView.swift
- Mammoth/Views/Cells/DetailView.swift
- Mammoth/Views/Cells/PostView.swift
- no longer use NLLanguageRecognizer which doesn't work for some languages (e.g., Latvian)
- don't specify a source language to the translator (use 'auto')
- no longer show the source language in the UI
- remove unused functions detectedLanguage
> MAM-3527-translation-not-working-build-v-202-build-349

- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
https://linear.app/theblvd/issue/MAM-3570/users-profile-should-update-to-show-newly-sent-post
> MAM-3570-users-profile-should-update-to-show-newly-sent-post

- Mammoth/Managers/AccountsManager/AccountsManager.swift
- fix the use of 'firstIndex' when looking for an account to update
> MAM-3593-fix-an-issue-where-sometimes-users-re-experienced-onboarding

- Mammoth/Models/PostLanguages.swift
Store the selected language correctly.
It was using the wrong key (one is postLanguage, and one is postLanguages)
> MAM-3600-user-reports-that-post-languages-dont-stick-across-app-launches

- Mammoth/Screens/Settings/IconSettingsViewController.swift
Fix from the internet…
Note: I was able to see this on the iPhone 15 Pro Max simulator, slowly scrolling and staring at the bottom row as it became visible.
> MAM-3592-app-icons-lag-when-loadingmisaligned-at-the-bottom

- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
Remove unnecessary parent menu.
> MAM-3588-follows-feed-context-menu-a-little-broken-on-macos

- Mammoth/Screens/iPad/SidebarViewController.swift
I was unable to reproduce the issue directly. Through code inspection, a nil superview will cause a crash, so I added a check for that.
> MAM-3615-crash-in-sidebarviewcontrollerdidmovetoparent

- Mammoth/Models/UserCardModel.swift
- Mammoth/Screens/UserListScreen/UserListViewModel.swift
- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
- use UserCardModel.isFollowing to track if the user is following this account (it doesn't appear to be used for any other purpose)
- when creating the list of UserCardModels for the 'Following" list, set this to true
- include checking this flag when creating the contextual menu
> MAM-3587-add-to-list-context-menu-sometimes-broken-on-macos

- Mammoth/Services/Backend/StatusService.swift
- Mammoth/Utils/PostActions.swift
[MAM-3617 : Post actions called on original status instead of local status](https://linear.app/theblvd/issue/MAM-3617/post-actions-called-on-original-status-instead-of-local-status)
Some of the post actions were using the "synced" status instead of the status from the user's instance. When we sync a post, we query the original post and update the PostCardModel with it's original status. We store the local status under preSyncedData. Use that status for post actions instead.
> MAM-3617-post-actions-called-on-original-status-instead-of-local

- Mammoth/Utils/EmailHandler.swift
- added support for Proton URL
- stop iterating over mail apps if there's a success
Annoyingly, Proton strips out the /n from the body (I even tried switching to \r to see if it made a difference; it didn't).
> MAM-3611-add-support-for-proton-mail

- Mammoth.xcodeproj/project.pbxproj
- Mammoth/Screens/Composer/NewPostViewController.swift
- Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
- Mammoth/Screens/Settings/ComposerSettingsViewController.swift
- Mammoth/Screens/Settings/ContactSettingsViewController.swift
- Mammoth/Screens/Settings/HapticsSettingsViewController.swift
- Mammoth/Screens/Settings/NotificationSettingsViewController.swift
- Mammoth/Screens/Settings/SettingsViewController.swift
- Mammoth/Screens/Settings/SiriSettingsViewController.swift
- Mammoth/Utils/SettingsIcons.swift
- Mammoth/Views/Cells/SelectionCell.swift
Create helper functions to create a fixed-size canvas, and draw the settings image in it, centered horizontally.
- create the helper functions for FontAwesome and SystemImage glyphs
- use the functions in the various settings ViewControllers
- remove some unused UITableView cell registrations
- adjust some constraints of the SelectionCell image
> MAM-3371-bd-misaligned-icontext-in-settings

- Mammoth/Managers/AccountsManager/AccountsManager.swift
- Mammoth/Managers/AccountsManager/AcctData.swift
- Mammoth/Managers/AccountsManager/AcctHandler.swift
- Mammoth/Screens/ProfileScreen/ProfileViewController.swift
- use UserDefaults to track accounts that have onboarded
- added a one-time migration of acctData.wentThroughOnboarding
- mark wentThroughOnboarding as deprecated
- remove uses of wentThroughOnboarding
> MAM-3620-sometimes-app-doesnt-remember-that-ive-onboarded

- Mammoth/Utils/PostActions.swift
iPads need a popoverPresentationController with a sourceView
> MAM-3621--ipados]-app-crash-when-sharing-post

- Mammoth/Models/UserCardModel.swift
- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
- Mammoth/Services/Backend/MastodonKit/Models/Relationship.swift
- Mammoth/Utils/PostActions.swift
[MAM-3623 : Correctly update follow status on Profile screen](https://linear.app/theblvd/issue/MAM-3623/correctly-update-follow-status-on-profile-screen)
When we don't have relationship information for a user we query that when opening a profile screen. The state of the follow button didn't update anymore to the correct state when the relationship object loaded.
> MAM-3623-correctly-update-follow-status-on-profile-screen

- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
[MAM-3624 : Stop videos in quote posts when cell is not visible](https://linear.app/theblvd/issue/MAM-3624/stop-videos-in-quote-posts-when-cell-is-not-visible)
> MAM-3624-stop-videos-in-quote-posts-when-cell-is-not-visible

- Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
When a follow button is displayed in the post card header and you open the post' detail screen you see a flickering of the follow button. You shouldn't
[MAM-3625 : Remove Follow button flickering on detail screen](https://linear.app/theblvd/issue/MAM-3625/remove-follow-button-flickering-on-detail-screen)
https://github.com/TheBLVD/mammoth/assets/221925/5429b51a-b377-4deb-8c79-7815daa9bc7e
> MAM-3625-remove-follow-button-flickering-on-detail-screen

- Mammoth/Utils/PostActions.swift
- Mammoth/Utils/UserActions.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift
- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
[MAM-3619 : Make 'Report user/post' menu items red; add confirmation alert](https://linear.app/theblvd/issue/MAM-3619/make-report-userpost-menu-items-red-add-confirmation-alert)
> MAM-3619-make-report-userpost-menu-items-red-add-confirmation-alert

- Mammoth/Screens/iPad/SidebarViewController.swift
If the same button is pushed again, just pop other viewControllers.
> MAM-3632-on-ipad-tapping-mentions-doesnt-go-back-to-mentions-view

- Mammoth/Views/Cells/SelectionCell.swift
- removed unused metrics dictionary
- adjusted the margin before and after the row image
> MAM-3629-some-settings-label-alignment-issues

- Mammoth/Models/ActivityCardModel.swift
- Mammoth/Services/Backend/TimelineService.swift
Show `status` notification instead of `update` notifications on Updates tab on Activity screen
[MAM-3650 : Fix the Activity Updates tab](https://linear.app/theblvd/issue/MAM-3650/fix-the-activity-updates-tab)
> MAM-3650-fix-the-activity-updates-tab

- Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
[MAM-3651 : Fix bad Link preview text clipping](https://linear.app/theblvd/issue/MAM-3651/fix-bad-link-preview-text-clipping)
> MAM-3651-fix-bad-link-preview-text-clipping

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
[MAM-3656 : Change Activity label from updated to edited](https://linear.app/theblvd/issue/MAM-3656/change-activity-label-from-updated-to-edited)
> MAM-3656-change-activity-label-from-updated-to-edited

- Mammoth/Screens/ActivityScreen/ActivityViewController.swift
[MAM-3659 : Rename the Update tab into Posts on the Activity tab](https://linear.app/theblvd/issue/MAM-3659/rename-the-update-tab-into-posts-on-the-activity-tab)
> MAM-3659-rename-the-update-tab-into-posts-on-the-activity-tab

- Mammoth.xcodeproj/project.pbxproj
- Mammoth/Utils/Extensions/String+StripEmojis.swift
- Mammoth/Views/Cells/ChannelCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardHeaderExtension.swift
[MAM-3658 : Remove emoji shortcodes from channel creator names and reblogger names?](https://linear.app/theblvd/issue/MAM-3658/remove-emoji-shortcodes-from-channel-creator-names-and-reblogger-names)
Stripping emojis from Smart List owner display names and from Reblog display names
> MAM-3658-remove-emoji-shortcodes-from-channel-creator-names-and

- Mammoth/Screens/Composer/NewPostViewController.swift
- if either (A) looking up a post ID, or (B) sending a post fails, put up an alert
- the alert has three choices (retry, save draft, discard)
- remove self.tableView.cellForRow check in saveDraft()
(checking for the cell existence used to be used for getting the post text, but no longer)
Note that the diff for saveDraft() looks big, but just the first line was removed, and then out-dented.
> MAM-3635-failed-to-post-to-mothsocial-3-times-in-a-row

- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
- Mammoth/Views/Cells/ChannelCell.swift
- use the profile's instance in ProfileViewModel.reloadUser()
- use the Smart List owner's domain/instance when possible
> MAM-3669-v2-not-using-remote-instances-for-post-fetching

- Mammoth.xcodeproj/project.pbxproj
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
[MAM-3692 : Performance: switch PostCard MetaText to MetaLabel](https://linear.app/theblvd/issue/MAM-3692/performance-switch-postcard-metatext-to-metalabel)
> MAM-3692-performance-switch-postcard-metatext-to-metalabel

- Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
- Mammoth/Services/Backend/MastodonKit/Client.swift
- Mammoth/Services/Backend/MastodonKit/ClientError.swift
- add a ClientError.networkError (with a status code) for network errors
- throw this error when necessary
- retry timeline requests for status code 206 and 500
> MAM-3708-retry-loading-feed-if-the-user-returns-a-500

- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
Only set the avatar image if self.user hasn't changed between the request and return of the image.
> MAM-3661-user-infoavatar-wrong-in-for-you-for-a-few-seconds-in-feed

- Mammoth/Screens/Settings/SettingsViewController.swift
- Mammoth/Views/Cells/UpgradeCell.swift
MOVED TO DRAFT UNTIL WE AGREE ON WHAT TO DO HERE
- change description of setting app icon if not supported by the platform
- hide the app icon setting row if not supported by the platform
> MAM-3680-setting-app-icon-doesnt-work-on-macos

- Mammoth/Views/CustomVideoPlayer.swift
Videos can now be scrubbed in fullscreen custom video player
[MAM-3677 : Videos in Mammoth can't be scrubbed](https://linear.app/theblvd/issue/MAM-3677/videos-in-mammoth-cant-be-scrubbed)
> MAM-3677-videos-in-mammoth-cant-be-scrubbed

- Mammoth/Utils/Extensions/UITableView+SafeScrollToRow.swift
- Mammoth/Utils/Protocols/Jumpable.swift
- Tentative fix for scroll-to-top when no indexPath is found
- More error logging
[MAM-3705 : Make double-tap Home more bullet proof](https://linear.app/theblvd/issue/MAM-3705/make-double-tap-home-more-bullet-proof)
> MAM-3705-make-double-tap-home-more-bullet-proof

- Mammoth/Models/UserCardModel.swift
- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
- Mammoth/Services/Backend/MastodonKit/Models/HashType.swift
Support custom emojis in info&link titles
[MAM-3699 : Custom Emojis in Info and Links not displaying](https://linear.app/theblvd/issue/MAM-3699/custom-emojis-in-info-and-links-not-displaying)
> MAM-3699-custom-emojis-in-info-and-links-not-displaying

- Mammoth/Utils/Extensions/UIImageView+Caching.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
[MAM-3728 : Wrong Avatar/Images displayed while Feed loads](https://linear.app/theblvd/issue/MAM-3728/wrong-avatarimages-displayed-while-feed-loads)
> MAM-3728-wrong-avatarimages-displayed-while-feed-loads

- Mammoth/Utils/Extensions/String+StripEmojis.swift
pfefferle reports an instant crash on app launch.
[MAM-3735 : Fix crash by stripEmojis function](https://linear.app/theblvd/issue/MAM-3735/fix-crash-by-stripemojis-function)
> MAM-3735-fix-crash-by-stripemojis-function

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
When fetching a post returns a 404 (in feed sync logic), do a webfinger lookup and only delete the post if the account is federated.
[MAM-3451 : “Post removed” showing for multiple people in Feeds](https://linear.app/theblvd/issue/MAM-3451/post-removed-showing-for-multiple-people-in-feeds)
> MAM-3451-post-removed-showing-for-multiple-people-in-feeds

- Mammoth/Screens/Registration/SignInViewController.swift
[MAM-3707 : When login into custom server, accept https](https://linear.app/theblvd/issue/MAM-3707/when-login-into-custom-server-accept-https)
- strip https:// from instance name input when adding new account
When using https://moth.social the app returned an error. Trim the input into moth.social.
> MAM-3707-when-login-into-custom-server-accept-https

- Mammoth/Services/Backend/MastodonKit/Models/Status.swift
The `bookmarked` property was missing from the coding keys in the `Status` class, which means that no remotely bookmarked statuses would ever have their bookmarked property set true, preventing them from being correctly displayed, or capable of being removed within the app.
This is the updated PR with a signed commit.
> Adding missing 'bookmarked' CodingKey to Status class

- Mammoth.xcodeproj/project.pbxproj
These were set to main/master. They have been changed as follows:
MessageKit - 4.0.0+
SDWebImage - 5.0.0+
Kingfisher - 7.0.0+
Reachability - a specific commit as it's version format doesn't work with Xcode (v5.1.0)
Before:
After:
> MAM-3732-set-all-dependencies-to-fixed-versions

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
[MAM-3756 : Limit preview text in activity to two lines](https://linear.app/theblvd/issue/MAM-3756/limit-preview-text-in-activity-to-two-lines)
> MAM-3756-limit-preview-text-in-activity-to-two-lines

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
[MAM-3752 : Multi image posts in activity are not properly defaulting to small](https://linear.app/theblvd/issue/MAM-3752/multi-image-posts-in-activity-are-not-properly-defaulting-to-small)
> MAM-3752-multi-image-posts-in-activity-are-not-properly-defaulting-to

- Mammoth/Services/Backend/MastodonKit/Foundation/Decodable.swift
Handle and log various JSON decoder error types.
> MAM-3764-add-more-descriptive-logging-to-parsing-errors

- Mammoth/Models/PostCardModel.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
[MAM-3757 : Don’t show thumbnails for likes and reposts in activity.](https://linear.app/theblvd/issue/MAM-3757/dont-show-thumbnails-for-likes-and-reposts-in-activity)
... also, don't show quote posts and link cards (https://linear.app/theblvd/issue/MAM-3757/dont-show-thumbnails-for-likes-and-reposts-in-activity)
> MAM-3757-dont-show-thumbnails-for-likes-and-reposts-in-activity

- Mammoth.xcodeproj/project.pbxproj
- Mammoth/Screens/External/SKPhotoBrowser/SKPhoto.swift
- Mammoth/Screens/External/SKPhotoBrowser/SKPhotoBrowser.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMediaStack.swift
- Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
[MAM-3260 : Image carousels for posts ✨](https://linear.app/theblvd/issue/MAM-3260/image-carousels-for-posts-✨)
MISSING:
- Missing a fixed aspect ratio lock when the original image or video is outside the 16/9 or 9/16 ratio
- In some cases videos are not displayed in their right aspect ratio
- accept swipes outside the gallery frame when the touch is on content of the scrollview (overriding hitTest)
> MAM-3260-image-carousels-for-posts

- Mammoth/Screens/Composer/NewPostViewController.swift
> MAM-3769-make-custom-emoji-button-the-bold-variant

- Mammoth/Screens/ProfileScreen/ProfileViewController.swift
- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
When switching accounts, ProfileHeader.onUserActionPress was nil (and so, tapping the field resulted in nothing happening). Now, onUserActionPress is set when ProfileHeader is created.
Also: clear self.extraInfoConstraints once it's associated data has been cleared.
> MAM-3352-links-on-profiles-not-working-build-340

- Mammoth/Models/PostCardModel.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
Display gallery, stack, or no media in quote post, depending on Media Size setting.
Fix text labels when posts or quoted post has no post text but has some media ((image), (video), (carousel), (gif))
[MAM-3773 : Quote Post Carousels](https://linear.app/theblvd/issue/MAM-3773/quote-post-carousels)
> MAM-3773-quote-post-carousels

- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Add additional top margin on the gallery when there's no post text. (to prevent the scroll view content to overlap with the profile pic)
[MAM-3772 : Photo carousel no-text](https://linear.app/theblvd/issue/MAM-3772/photo-carousel-no-text)
> MAM-3772-photo-carousel-no-text

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
[MAM-3770 : Link boxes should match the width of the rest of the column](https://linear.app/theblvd/issue/MAM-3770/link-boxes-should-match-the-width-of-the-rest-of-the-column)
> MAM-3770-link-boxes-should-match-the-width-of-the-rest-of-the-column

- Mammoth/Models/PostCardModel.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
[MAM-3778 : Capitalize GIF label in small/hidden media mode](https://linear.app/theblvd/issue/MAM-3778/capitalize-gif-label-in-smallhidden-media-mode)
> MAM-3778-capitalize-gif-label-in-smallhidden-media-mode

- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
[MAM-3786 : Carousel should go over thread lines not under.](https://linear.app/theblvd/issue/MAM-3786/carousel-should-go-over-thread-lines-not-under)
> MAM-3786-carousel-should-go-over-thread-lines-not-under

- Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
- Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
- Redoing image and video constraints for a fix-height environment (as we have in the gallery)
- Clip to 16/9 ratio constraints when exceeding that ratio, with the exception of tall portraits to accept iPhone 15 Pro screenshots without clipping
[MAM-3781 : Long images rendering wrong in carousels](https://linear.app/theblvd/issue/MAM-3781/long-images-rendering-wrong-in-carousels)
> MAM-3781-long-images-rendering-wrong-in-carousels

- Mammoth/Screens/ProfileScreen/ProfileViewModel.swift
When visiting someone's profile we fetch the user object from its original instance and replace the user object (UserCardModel) in ProfileViewModel with it. Later, we recreated the user instead of mutating it to update the user but forgot to copy over the instanceName. This lead to a broken pagination on profile screen when the original user was from a different instance as the logged in instance. 
[MAM-3787 : Fix profile pagination errors after user sync](https://linear.app/theblvd/issue/MAM-3787/fix-profile-pagination-errors-after-user-sync)
> MAM-3787-fix-profile-pagination-errors-after-user-sync

- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
Make the carousel height variable based on the screen width, and max 260px
[MAM-3780 : Image in carousels should never have thumbnails wider than the content area.](https://linear.app/theblvd/issue/MAM-3780/image-in-carousels-should-never-have-thumbnails-wider-than-the-content)
Tested on iPhone SE, iPhone 15 Pro and Mac
> MAM-3780-image-in-carousels-should-never-have-thumbnails-wider-than

- Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
[MAM-3775 : Dismiss fullscreen carousel into the correct image](https://linear.app/theblvd/issue/MAM-3775/dismiss-fullscreen-carousel-into-the-correct-image)
https://github.com/TheBLVD/mammoth/assets/221925/8edee6dc-8df9-4f00-a543-1effd13ccbbe
> MAM-3775-dismiss-fullscreen-carousel-into-the-correct-image

- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
[MAM-3741 : Post sync logic should use the user's instance, not moth.social](https://linear.app/theblvd/issue/MAM-3741/post-sync-logic-should-use-the-users-instance-not-mothsocial)
> MAM-3741-post-sync-logic-should-use-the-users-instance-not-mothsocial

- Mammoth/Managers/HashtagManager.swift
[MAM-3788 : Prevent infinite loop when fetchFollowingTags fails](https://linear.app/theblvd/issue/MAM-3788/prevent-infinite-loop-when-fetchfollowingtags-fails)
> MAM-3788-prevent-infinite-loop-when-fetchfollowingtags-fails

- Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
- Attempt to decrease jumpy swipes by preloading images in the background
- Use a blurhash image placeholder if image is not yet preloaded
[MAM-3771 : Jumpy swipes when fullscreening a carousel.](https://linear.app/theblvd/issue/MAM-3771/jumpy-swipes-when-fullscreening-a-carousel)
> MAM-3771-jumpy-swipes-when-fullscreening-a-carousel

- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
[MAM-3791 : Tapping on Post Details for uploaded Video with "Media == Small" shows wrong Post](https://linear.app/theblvd/issue/MAM-3791/tapping-on-post-details-for-uploaded-video-with-media-==-small-shows)
> MAM-3791-tapping-on-post-details-for-uploaded-video-with-media-small

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
[MAM-3794 : Media helper text in small-mode only for status notifications](https://linear.app/theblvd/issue/MAM-3794/media-helper-text-in-small-mode-only-for-status-notifications)
It should only be saying (Carousel) in New Post notifications (in small-media mode)
> MAM-3794-media-helper-text-in-small-mode-only-for-status

- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
[MAM-3800 : Image carousels misalign when exiting](https://linear.app/theblvd/issue/MAM-3800/image-carousels-misalign-when-exiting)
> MAM-3800-image-carousels-misalign-when-exiting

- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Caching.swift
Avoid creating an invalid array / crash.
> MAM-3792-crash-in-newsfeedviewmodelsavetodisk

- Mammoth/Services/Backend/MastodonKit/ClientError.swift
Create specific error descriptions for specific error types.
In the crash case, it was a .networkError() that was calling self.localizedDescription, which in turn called ClientError.errorDescription.
I was able to simulate a network status code of 500, and see the alert as expected.
> MAM-3806-crash-when-attaching-image-if-server-returns-status-code-500

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel+DataSource.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
- Mammoth/Screens/HomeScreen/Views/UnreadIndicator.swift
Clearing the unread indicator and tab bar indicator in a more reliable way.
[MAM-3634 : Activity Notifications: Notification dots not clearing after checking](https://linear.app/theblvd/issue/MAM-3634/activity-notifications-notification-dots-not-clearing-after-checking)
> MAM-3634-activity-notifications-notification-dots-not-clearing-after

- Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
Create media components once in setupUI and use isHidden to show/hide when needed. This should prevent duplicate media creation. This brings it also more inline with the architecture of the PostCardCell.
[MAM-3817 : Fix ActivityCardCell repeated media bug](https://linear.app/theblvd/issue/MAM-3817/fix-activitycardcell-repeated-media-bug)
> MAM-3817-fix-activitycardcell-repeated-media-bug

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
- hide the gallery carousel if there's content warning / content deleted overlay
- fix an issue where the hitTest was called for unrelated cells causing unresponsive and unpredictable behavior
[MAM-3824 : carousel stack layout issue](https://linear.app/theblvd/issue/MAM-3824/carousel-stack-layout-issue)
> MAM-3824-carousel-stack-layout-issue

- Mammoth/Screens/Composer/EmoticonPickerViewController.swift
- Mammoth/Screens/Composer/NewPostViewController.swift
Use the custom emojis of the server of the current account in the composer, instead of the emojis of the current account in the rest of the app.
[MAM-3829 : Switching profiles from compose screen doesn't change the custom emoji picker.](https://linear.app/theblvd/issue/MAM-3829/switching-profiles-from-compose-screen-doesnt-change-the-custom-emoji)
> MAM-3829-switching-profiles-from-compose-screen-doesnt-change-the

- Mammoth/Utils/Extensions/View/UIColor+Asset.swift
AppCol is global, regardless of high/regular contrast.
> MAM-3863-crash-on-build-26-394-from-bart

- Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
- add a .highContrast enum for a UISwitch row
- only expose the switch on iOS 17+
- handle enum cases appropriately
- remove the Light / Dark High Contrast rows
> MAM-3859-add-a-high-contrast-toggle-to-settings-appearance

- Mammoth/Assets/Assets.xcassets/Colors/FAB Background.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/Colors/FAB Foreground.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/Colors/High Contrast.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/Colors/Poll Bar Text.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/Colors/Poll Bars.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCFAB Background.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCFAB Foreground.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCOVRLY Med Contrast.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCOVRLY Soft Contrast.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCPoll Bar Text.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCPoll Bars.colorset/Contents.json
- Mammoth/Assets/Assets.xcassets/HCColors/HCSoft Contrast.colorset/Contents.json
- Mammoth/Utils/Extensions/View/UIColor+Asset.swift
- Mammoth/Views/Cells/PostCardCell/PostCardPoll.swift
- Mammoth/Views/NewPostButton.swift
- update various contrast colors
- add new colors poll text, poll bar, and 'new post' button colors
- use the new colors for poll text, and poll bars
- use new FAB colors for the New Post Button (and remove the blurEffectView
> MAM-3892-updateverify-some-contrast-poll-text-and-new-post-button-colors

- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardHeader.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardFooter.swift
- Mammoth/Views/Cells/PostCardCell/PostCardHeader.swift
- Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
- Mammoth/Views/Cells/PostCardCell/PostCardLinkPreview.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
- Fixed header background colors
- Set a background colors to most of the views in PostCardCell and its child views
- Move theming logic to `onThemeChange` method
- Fixing additional theming issues related to high contracts mode
[MAM-3893 : Toggling High Contrast off discolors Activity Tab notif headers](https://linear.app/theblvd/issue/MAM-3893/toggling-high-contrast-off-discolors-activity-tab-notif-headers)
> MAM-3893-toggling-high-contrast-off-discolors-activity-tab-notif

- Mammoth/Views/BlurredBackground.swift
- Mammoth/Views/NewPostButton.swift
[MAM-3891 : Nav bars and toolbars arent blending on high contrast dark mode.](https://linear.app/theblvd/issue/MAM-3891/nav-bars-and-toolbars-arent-blending-on-high-contrast-dark-mode)
> MAM-3891-nav-bars-and-toolbars-arent-blending-on-high-contrast-dark

- Mammoth/Screens/HomeScreen/Views/Carousel/Carousel.swift
- Mammoth/Screens/HomeScreen/Views/Carousel/CarouselFlowLayout.swift
[MAM-3895 : Make inactive carousel items less bright in HC-mode](https://linear.app/theblvd/issue/MAM-3895/make-inactive-carousel-items-less-bright-in-hc-mode)
Making the active carousel item pop by putting the inactive items on 65% opacity. Only in high-contrast mode.
> MAM-3895-make-inactive-carousel-items-less-bright-in-hc-mode

- Mammoth/Screens/DiscoveryScreen/DiscoverSuggestionsViewModel.swift
I ended up doing both of these, as they were so related:
https://linear.app/theblvd/issue/MAM-3882/filter-out-known-followed-accounts-client-side
https://linear.app/theblvd/issue/MAM-3883/randomize-suggested-follows-client-side
- filter out accounts that are known to be followed
- randomize the results
> MAM-3882-filter-out-known-followed-accounts-client-side

- Mammoth/Models/PostCardModel.swift
Currently the `PostCardModel.mergeInOriginalData()` method (used for syncing accurate like, repost and reply counts) will cause the bookmarked property to be overwritten. Since bookmark status is only accurate when you're querying your home Mastodon server, this property is always being trampled.
This PR simply makes the bookmarks property unable to be made false by a merge, if it was previously true.
> Prevent the bookmark property from being incorrectly overwritten

- Mammoth/Managers/StatusCache.swift
- Mammoth/Screens/Settings/SettingsViewController.swift
During my bookmark testing I noticed we did not purge any of the state accumulated in `StatusCache`, so this adds a basic method and hooks it up to `SettingsViewController.clearAllCaches()`.
> Add clearCache() to StatusCache and hook up to clearAllCaches()

- Mammoth/Screens/HomeScreen/Views/Carousel/Carousel.swift
- Mammoth/Screens/HomeScreen/Views/Carousel/CarouselItem.swift
[MAM-3926 : Nav cleanup: carousel item context menu without blur](https://linear.app/theblvd/issue/MAM-3926/nav-cleanup-carousel-item-context-menu-without-blur)
https://github.com/TheBLVD/mammoth/assets/221925/6b4355bf-c9f1-4286-9a70-f36ca5b23fb9
> MAM-3926-nav-cleanup-carousel-item-context-menu-without-blur

- Mammoth/Screens/DiscoveryScreen/PostResultsViewModel.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
Refactor how we configure the quote post UI. Instead of creating it in`configure(...)` (in realtime) we create all elements once in `setupUI()` and use .isHidden to enable what we need in `configure()`. This approach is what we started doing in all major cell components.
[MAM-3907 : Repetition bug in quote posts](https://linear.app/theblvd/issue/MAM-3907/repetition-bug-in-quote-posts)
> MAM-3907-repetition-bug-in-quote-posts

- Mammoth/Managers/AccountsManager/AccountsManager.swift
- Mammoth/Managers/AccountsManager/AcctData.swift
- Mammoth/Screens/DiscoveryScreen/DiscoveryViewModel.swift
- Mammoth/Services/Backend/AccountService.swift
- Mammoth/Services/Backend/ClientService.swift
- Mammoth/Services/Backend/MastodonKit/Requests/Accounts.swift
- stop requesting follow suggestions in DiscoverViewModel (the model used for showing Account search results; it doesn't need the suggestions)
- create a featureClient, similar to client, mothClient
- use the featureClient to get follow suggestions
> MAM-3928-use-new-follow-suggestions-endpoint

- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
An exception was being thrown when attempting to display "Post could not be found" as the postNotFound view was not in the view hierarchy.
> MAM-3934-invalid-quote-causing-crash

- Mammoth/Views/AccountSwitcherButton.swift
Use the proper menu structure for macOS as needed.
> MAM-3946-macos-account-switcher-bug-in-27

- Mammoth/Screens/DiscoveryScreen/DiscoveryViewModel.swift
Reinstate the initial request for account content. It's not needed for iPhone, but is for iPad/macOS.
> MAM-3951-macos-no-suggested-follows

- Mammoth/Views/AccountSwitcherButton.swift
- Mammoth/Views/Cells/PostCardCell/PostCardProfilePic.swift
- use the correct border color in the account switcher button when the theme updates
- always use a circle transform for the account button
- re-set the main profile avatar image when changing between square/circle
> MAM-3950-avatar-top-left-on-profile-buggy

- Mammoth/Screens/ForYouCustomizationScreen/ForYouCustomizationViewModel.swift
Hide the 'beta' / third section in the For You customization view.
> MAM-3972-remove-for-you-beta-features

- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
this choice was made because on authenticated requests, these are handled by the server.
> Only run filters and blocks client-side on remote feeds.

- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
https://linear.app/theblvd/issue/MAM-3984/fix-issue-with-blank-profile-pic-on-profile-screen
> MAM-3984-fix-issue-with-blank-profile-pic-on-profile-screen

- Mammoth/Services/Backend/MastodonKit/Models/Account.swift
- Mammoth/Utils/UserActions.swift
On a user profile page, if you select "Mention" from the top right menu, it incorrectly misses out the '@' prefix for the full username. I've added it, plus changed the comments in UserActions to be clearer about what is happening.
> Fix issue with the '@' prefix not being added appropriately in Mention function

- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
- Mammoth/Views/Cells/ActivityCardCell/ActivityCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
- Mammoth/Views/Cells/PostCardCell/PostCardQuotePost.swift
- Mammoth/Views/Cells/UserCardCell/UserCardCell.swift
> MAM-3989-bigger-line-breaks

- .arkana.yml
- Mammoth.xcodeproj/project.pbxproj
- Mammoth/Models/GlobalStruct.swift
- Mammoth/SceneDelegate.swift
- Mammoth/Services/l10n/CrowdinService.swift
- sample.env
This is an important step in our l10n workflow. With these changes we need to explicitly enable a language in our codebase. Even if translations on crowdin are approved and downloaded in our xcstring files, a language will only be used if it is in the `supportedLocalizations` array (https://github.com/TheBLVD/mammoth/compare/MAM-4018-client-side-fallback-to-only-enable-supported-languages?expand=1#diff-1e390366736fb502afd833b0a67be240fc83822ed4b39b3e8bf332839df7def8R26)
This will function as an extra step in enabling new languages, which gives us more control. 
This will allow us to easily create (Testflight) builds with specific languages enabled or disabled, or have a system enabling languages for specific users.
> MAM-4018-client-side-fallback-to-only-enable-supported-languages

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
Storing deferred snapshot updates in an array and executing them when scrolling ended was probably a bad design. When calling the deferred snapshot updates the scroll position was often not retained, which led to feed jumps.
In this PR, we don't store deferred snapshot updates but instead apply the latest snapshot changes once, when scrolling stops.
https://linear.app/theblvd/issue/MAM-4022/feed-stability-work
> MAM-4022-feed-stability-work

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
https://linear.app/theblvd/issue/MAM-4026/interaction-count-not-updating-in-the-timeline
> MAM-4026-interaction-count-not-updating-in-the-timeline

- Mammoth/Views/AnimatedTabBar.swift
https://linear.app/theblvd/issue/MAM-3982/navigator-gets-misaligned-with-different-string-sizes
> MAM-3982-navigator-gets-misaligned-with-different-string-sizes

- Mammoth/Screens/ProfileScreen/Views/ProfileHeader.swift
https://linear.app/theblvd/issue/MAM-4054/profile-follower-count-gets-cut-off-l10n
> MAM-4054-profile-follower-count-gets-cut-off-l10n

- Mammoth/Views/Cells/PostCardCell/PostCardMetadata.swift
https://linear.app/theblvd/issue/MAM-4053/interaction-counts-get-cut-off-in-other-languages
> MAM-4053-interaction-counts-get-cut-off-in-other-languages

- Mammoth/Managers/StatusCache.swift
- Mammoth/Models/PostCardModel.swift
- Mammoth/Services/Backend/MastodonKit/Models/Status.swift
- Mammoth/Services/Backend/MastodonKit/Requests/Search.swift
allows us to render every fediverse object as a quote post, rather than only mastodon stuff, also as a bonus makes quoting conform to the instance's moderation, since the user's instance fetches the post.
this is mainly a POC, currently incompatible with ivory because they just append the link under the post.
images: (can i make these smaller?)
> MAM-3626-consider-use-url-search-on-instance-to-get-quote-post-from

- Mammoth/Views/NewPostButton.swift
https://linear.app/theblvd/issue/MAM-4066/align-newpost-button-arrow-on-mac
> MAM-4066-align-newpost-button-arrow-on-mac

- Mammoth/Screens/ActivityScreen/ActivityViewController.swift
- Mammoth/Screens/iPad/AuxFeedViewController.swift
- Mammoth/Views/CarouselNavigationHeader.swift
https://linear.app/theblvd/issue/MAM-4074/fix-activity-header-in-aux-column-on-ipad
> MAM-4074-fix-activity-header-in-aux-column-on-ipad

- Mammoth/Views/Cells/PostCardCell/PostCardMediaGallery.swift
also removes the need for resizing blurhashes.
> MAM-4099-unloaded-images-in-carousel-have-wrong-width

- Mammoth/Models/NewsFeedListItem.swift
- Mammoth/Models/PostCardModel.swift
- Mammoth/Services/Backend/StatusService.swift
- Mammoth/Utils/PostActions.swift
i basically inverted our logic. instead of overwriting the `.data` parameter and keeping a backup in `.preSyncData`, i'm keeping `.data` the original data and only writing new data to `.remoteData`, which is only used for interactions and app name.
i think this is a good quick fix for weird ID behavior until we figure out a better solution.
> MAM-3914-dont-replace-every-post-data-when-fetching-for-interaction

- Mammoth/Screens/HomeScreen/HomeViewController.swift
- Mammoth/Views/AccountSwitcherButton.swift
I don't have a way to test this at the moment since you need developer account access to add physical devices. I think this is the right change based on what I found in the other context menu items.
I added haptic impact light to the home menu items as well as a missing one from the profile context menu. There were also a few lines of spaces cleaned up. Otherwise, minor changes here. Please let me know if this is every spot for this. I'm trying to have a small feedback when the long press presents this menu:
It already presents a feedback only when tapping the Add account button. I added one for changing accounts here:
If I'm missing one, which I think I might be, let me know and I can update to add it in the correct spot.
> Add haptics for home menu items

- Mammoth/Screens/Settings/AppearanceSettingsViewController.swift
Fixed an issue where the usertag localization was not being used when the value was set.
> Missing Usertag Value Localization

- Mammoth/Localizable.xcstrings
- Mammoth/Views/Cells/PostCardCell/PostCardCell.swift
Re-introduced localized strings, and fixed an issue where there was too much space after posts with no media in full width mode.
> Full Width Post Fixes

- Mammoth.xcodeproj/project.pbxproj
Moved versions to be defined on the project rather than individual targets so they stay in sync:
This prevents issues like this from cropping up by having a single place to make changes:
> Extension Version Mismatch

- Mammoth/Models/PostCardModel.swift
- Mammoth/Screens/Composer/NewPostViewController.swift
- Mammoth/Services/Backend/MastodonKit/Client.swift
- Mammoth/Services/Backend/MastodonKit/Models/Attachment.swift
- Mammoth/Views/Cells/DetailImageView.swift
- Mammoth/Views/Cells/PostCardCell/PostCardImage.swift
- Mammoth/Views/Cells/PostCardCell/PostCardImageAttachment.swift
- Mammoth/Views/Cells/PostCardCell/PostCardMediaStack.swift
- Mammoth/Views/Cells/PostCardCell/PostCardVideo.swift
- Mammoth/Views/Cells/PostView.swift
This fixes MAM-4155 (#593), with a further followup after merging at MAM-4159
> MAM-4155: Allow all 2xx status codes to be recognized as success

- Mammoth/AppDelegate.swift
- Mammoth/Models/GlobalStruct.swift
- Mammoth/Screens/Settings/OpenLinksSettingsViewController.swift
- Mammoth/Screens/Settings/SettingsViewController.swift
- Mammoth/Utils/LinkOpener.swift
- renaming browser option "Mammoth" to "In-app browser"
- only showing "reader view" option when "In-app browser" is being used
- making "in-app browser" the default
> MAM-4161-hide-reader-view-option-when-using-external-browser

- Mammoth/Info.plist
To stop app store connect from bugging every time
> MAM-4167: Add export compliance key 

- Mammoth/Screens/Composer/NewPostViewController.swift
- Mammoth/Services/Backend/MastodonKit/Requests/Search.swift
Tested on moth.social (the one originally broken), mastodon.social, my own mastodon server.
> Revert to v1 account search api for autocomplete only

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
If I'm reading this correctly, sometimes the new scrollPosition was being used in the place of the pre-updateScrollPosition.
I gave the pre-updateScrollPosition its own name, and used it where it made sense based on the comments.
> Use preUpdateScrollPosition

- Mammoth/Screens/HomeScreen/NewsFeedViewController.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel+Services.swift
- Mammoth/Screens/HomeScreen/NewsFeedViewModel.swift
- add a userHasScrolledManually: Bool flag to newsFeedViewModel
- set userHasScrolledManually to true in NewsFeedViewController.scrollViewWillBeginDragging()
- have scrollToCloudPosition() bail if this is set to true
> Skip iCloud sync if user has manually scrolled
